"""Shared helpers for VanguardCMA deploy/run/teardown scripts."""

from __future__ import annotations
import json
import os
import re
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
STATE_PATH = ROOT / ".deploy-state.json"
SKILLS_DIR = ROOT / "skills"
PROMPT_TEMPLATE = ROOT / "agent" / "system_prompt.md"
VANGUARD_YAML = ROOT / "vanguard.yaml"        # orchestration config (you edit this)
AGENT_YAML = ROOT / "agent.yaml"              # CMA-native manifest (generated)
SECRETS_ENV = ROOT / "secrets.env"

# Beta headers (memory store needs the research-preview one)
BETA_HEADERS = "managed-agents-2026-04-01,managed-agents-2026-04-01-research-preview"


def load_env() -> None:
    """Load secrets.env into os.environ if present."""
    if SECRETS_ENV.exists():
        load_dotenv(SECRETS_ENV)
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit(
            "ANTHROPIC_API_KEY missing. Copy secrets.env.example to secrets.env and fill in keys."
        )


def load_config() -> dict[str, Any]:
    """Load vanguard.yaml (the orchestration config). Bails if missing."""
    if not VANGUARD_YAML.exists():
        raise SystemExit(
            f"{VANGUARD_YAML} not found. "
            "Copy vanguard.yaml.example to vanguard.yaml and edit."
        )
    with VANGUARD_YAML.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_agent_manifest(
    config: dict[str, Any],
    system_prompt: str,
    skill_pins: dict[str, str],
    skill_ids: dict[str, str],
) -> None:
    """
    Materialize the CMA-native agent manifest to agent.yaml. This is the
    exact shape POST /v1/agents accepts — pasteable into the Anthropic
    console's Create-agent UI as an alternative to deploy.py.
    """
    a_cfg = config["agent"]
    skills_block = []
    for sname, sver in skill_pins.items():
        skills_block.append(
            {"type": "custom", "skill_id": skill_ids[sname], "version": sver}
        )

    manifest = {
        "name": a_cfg["name"],
        "description": a_cfg.get("description", ""),
        "model": a_cfg["model"],
        "system": system_prompt,
        "mcp_servers": [],
        "tools": [{"type": "agent_toolset_20260401"}],
        "skills": skills_block,
    }

    # Use block style for the system prompt (literal | scalar) for readability
    yaml.add_representer(
        str,
        lambda dumper, data: (
            dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
            if "\n" in data
            else dumper.represent_scalar("tag:yaml.org,2002:str", data)
        ),
    )
    AGENT_YAML.write_text(
        "# =============================================================\n"
        "# agent.yaml — CMA-native manifest, regenerated by deploy.py.\n"
        "# Pasteable into the Anthropic console's Create-agent YAML editor.\n"
        "# Edit vanguard.yaml instead — this file is overwritten on deploy.\n"
        "# =============================================================\n\n"
        + yaml.dump(manifest, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )


def load_state() -> dict[str, Any]:
    """Load .deploy-state.json (resource IDs from prior deploys). Empty if absent."""
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    return {}


def save_state(state: dict[str, Any]) -> None:
    """Persist resource IDs."""
    STATE_PATH.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def slugify(s: str) -> str:
    """Lowercase, hyphenated, ASCII-only. 'Robert Mondavi' -> 'robert-mondavi'."""
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def render_system_prompt(config: dict[str, Any]) -> str:
    """Substitute {{...}} placeholders in agent/system_prompt.md from vanguard.yaml."""
    template = PROMPT_TEMPLATE.read_text(encoding="utf-8")

    company = config["company"]
    slack_cfg = config["slack"]
    scoring = config["scoring"]
    sources = config["sources"]
    competitors = config["competitors"]

    # competitors_block — bulleted list with aliases + sources + per-source IDs
    sec_ciks = sources.get("sec", {}).get("competitor_ciks", {}) or {}
    gh_orgs = sources.get("github", {}).get("competitor_orgs", {}) or {}
    yt_chans = sources.get("youtube", {}).get("competitor_channels", {}) or {}

    comp_lines = []
    for c in competitors:
        name = c["name"]
        aliases = c.get("aliases") or []
        srcs = c.get("sources") or []
        line = f"- **{name}**"
        if aliases:
            line += f" (aliases: {', '.join(aliases)})"
        line += f" — sources: {', '.join(srcs)}"
        extras = []
        if name in sec_ciks:
            extras.append(f"sec_cik={sec_ciks[name]}")
        if name in gh_orgs:
            extras.append(f"github_org={gh_orgs[name]}")
        if name in yt_chans:
            extras.append(f"youtube_channel={yt_chans[name]}")
        if c.get("priority_multiplier"):
            extras.append(f"priority_multiplier={c['priority_multiplier']}")
        if extras:
            line += f" [{', '.join(extras)}]"
        comp_lines.append(line)
    competitors_block = "\n".join(comp_lines)

    # sources_block — which source types are globally on
    src_lines = []
    for src_name, cfg in sources.items():
        if cfg.get("enabled"):
            src_lines.append(f"- **{src_name}**")
    sources_block = "\n".join(src_lines) if src_lines else "(none enabled)"

    # channel_overrides_block
    overrides = slack_cfg.get("channel_overrides") or {}
    if overrides:
        lines = [f"- **{cat}** → `{cid}`" for cat, cid in overrides.items()]
        channel_overrides_block = "\n".join(lines)
    else:
        channel_overrides_block = "(none — all findings go to the default channel)"

    # source_baseline_block
    sb = scoring.get("source_baseline", {})
    source_baseline_block = "\n".join(f"  - {k}: {v}" for k, v in sb.items())

    # high_keywords_csv
    high_kw = scoring.get("high_keywords", [])
    high_keywords_csv = ", ".join(f"`{kw}`" for kw in high_kw)

    substitutions = {
        "company_name": company["name"],
        "company_slug": company["slug"],
        "context_skill_name": company["context_skill_name"],
        "memory_store_name": config["memory"]["store_name"],
        "competitors_block": competitors_block,
        "sources_block": sources_block,
        "default_channel": slack_cfg["default_channel"],
        "channel_overrides_block": channel_overrides_block,
        "low_priority_strategy": slack_cfg.get("low_priority_strategy", "roundup"),
        "high_keywords_csv": high_keywords_csv,
        "recency_cap_days": str(scoring.get("recency_cap_days", 7)),
        "source_baseline_block": source_baseline_block,
    }

    out = template
    for key, val in substitutions.items():
        out = out.replace("{{" + key + "}}", str(val))
    return out


def list_skill_dirs() -> list[Path]:
    """All skill directories that should be uploaded. Skips understanding-TEMPLATE."""
    skills: list[Path] = []
    for sub in (SKILLS_DIR / "core").iterdir():
        if sub.is_dir() and (sub / "SKILL.md").exists():
            skills.append(sub)
    for sub in (SKILLS_DIR / "custom").iterdir():
        if not sub.is_dir() or not (sub / "SKILL.md").exists():
            continue
        if sub.name == "understanding-TEMPLATE":
            continue  # template — don't upload as-is
        skills.append(sub)
    return skills


def get_anthropic_client():
    """Return an Anthropic client with beta headers wired via default_headers."""
    from anthropic import Anthropic

    return Anthropic(
        api_key=os.environ["ANTHROPIC_API_KEY"],
        default_headers={"anthropic-beta": BETA_HEADERS},
    )
